### ISSUE TITLE
Contribution detail page

### ISSUE THREAD

**Issue by shaharhalutz** [Backfeed/BF-API-Server#5]
just make things a little nicer with bootstrap - and display all necessary details:
lets start with showing 
- title
we want to show 3 separate panels:

1) 'my bids'-  the user's Bids (on this contribution) 
create new bid  - button (offcourse)
in this panel we show all the user's bids on this contribution
and also after a user makes HIS first bid on a certain contribution (he doesnt have to be the owner ) -only then - he should see a Status button and this button should call a 'getContributionStatus' query from the server and open a detail page called status Page.

(note:  all the other users  bids of the contribution should not be shown ,maybe just a debug button that prints- all the contribution bids to the console - for debug purposes)

2) 'content' (file)

3) 'collaborators' -  all the contribution collaborators

**Comment by jainmnit** [comment]
Done the changes
